apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-trigger
spec:
  params:
    - name: SERVICE_ACCOUNT
      description: trigger
    - name: URL
      description: url
    - name: dockerfile
      description: dockerfile to build from
    - name: NAMESPACE
      description: namespace
    - name: image-registry
      description: image location after build
    - name: pvc
      description: volume claim to be built on
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: kaniko-test-pipeline-run-2-3
    spec:
      serviceAccountName: $(params.SERVICE_ACCOUNT)
      pipelineRef:
        name: kaniko-test-pipeline
      params:
      - name: source
        value: $(params.URL)
      - name: image
        value: $(params.image-registry)
      - name: dockerfile
        value: $(params.dockerfile)
      workspaces:
      - name: build-zone
      persistantVolumeClaim:
        claimName: $(params.pvc)